### ISSUE TITLE
为什么我上传图片处理的时候正常不报错,一单把图片卸载了, 不用的时候就会报错,导致controlnet功能和其它功能无法正常使用

### ISSUE THREAD

**Issue by aaronkingdom** [continue-revolution/sd-webui-segment-anything#106]
Start SAM Processing
Initializing SAM
Running SAM Inference (1600, 1600, 3)
SAM inference with 0 box, 8 positive prompts, 2 negative prompts
Creating output image
Start SAM Processing
Initializing SAM
Running SAM Inference (1600, 1600, 3)
SAM inference with 0 box, 8 positive prompts, 2 negative prompts
Creating output image
Start SAM Processing
Initializing SAM
Running SAM Inference (1600, 1600, 3)
SAM inference with 0 box, 14 positive prompts, 9 negative prompts
Creating output image
Start SAM Processing
Initializing SAM
Running SAM Inference (1600, 1600, 3)
SAM inference with 0 box, 14 positive prompts, 9 negative prompts
Creating output image
Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 761, in process
    process_unit.set_process_attributes(p)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 87, in set_process_attributes
    inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_mask_blur)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 43, in get_input_and_mask
    mask = Image.open(self.dilation_output_gallery[1]['name']).convert('L')
TypeError: 'UiControlNetUnit' object is not subscriptable
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py", line 231, in process
    weight = float(weight)
ValueError: could not convert string to float: 'IN05-OUT05'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 258, in process
    elemental = elemental.split("\n\n") if elemental is not None else []
AttributeError: 'int' object has no attribute 'split'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1033, in process
    self.enabled_units = self.get_enabled_units(p)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 992, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 844, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'bool' object has no attribute 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process_batch: D:\AI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 294, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
AttributeError: 'Script' object has no attribute 'lratios'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

如标题:我上传图片处理的时候正常不报错,一单把图片卸载了, 不用的时候就会报错,导致controlnet功能和其它功能无法正常使用
我试过把segment anything 扩展关了, 就一切正常其它插件都不会报错,一单开启扩展而不用的时候就会报上面的错误.

用的是秋叶包,使用条件也符合了: 
python: 3.10.7  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)  •  checkpoint: [fc2511737a](https://google.com/search?q=fc2511737a54c5e80b89ab03e0ab4b98d051ab187f92860f3cd664dc9d08b271)

**Comment by aaronkingdom** [comment]
有大佬帮看看什么原因吗, 目前只能忍痛先关闭了

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything/issues/93#issuecomment-1546777860

**Comment by aaronkingdom** [comment]
对了,启动的时候也没有报错

**Comment by aaronkingdom** [comment]
> [#93 (comment)](https://github.com/continue-revolution/sd-webui-segment-anything/issues/93#issuecomment-1546777860)

在线啊大佬? 我去看看 希望能解决

**Comment by aaronkingdom** [comment]
> [#93 (comment)](https://github.com/continue-revolution/sd-webui-segment-anything/issues/93#issuecomment-1546777860)

牛皮, 就是这个问题, 改个名字就可以了...   看来很多人各种错误都是这样引起的, 在说明标注一下比较好吧...  安装的时候改个别名也可以解决

**Comment by aaronkingdom** [comment]
> > [#93 (comment)](https://github.com/continue-revolution/sd-webui-segment-anything/issues/93#issuecomment-1546777860)
> 
> 牛皮, 就是这个问题, 改个名字就可以了... 看来很多人各种错误都是这样引起的, 在说明标注一下比较好吧... 安装的时候改个别名也可以解决

额,我又报错回来了.............    必须要排序在第一才行???   我用controlnet, 把它放在后面会出错.......   不管了, 加A1111前缀,其它的字母+数字的排序比它小,让在排在webui的第一位就可以了....

**Comment by continue-revolution** [comment]
不一定，但是必须得在ControlNet前面。你所有的插件在底层是在一个list里面，这个list按照插件文件名排序。只有ControlNet前面的插件才能控制ControlNet。我的插件在制作的时候没有考虑ControlNet，为了克服这个问题在运行时改了这个list。
