### ISSUE TITLE
[Bug]: Mac M1 pro 预览报错: local variable 'install_success' referenced before assignment

### ISSUE THREAD

**Issue by kyosky110** [continue-revolution/sd-webui-segment-anything#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the latest version?

- [X] I have updated WebUI and this extension to the latest version

### Do you understand that you should read the 1st item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you understand that you should use the latest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### Do you understand that you should read the 2nd item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you observe problems like AttributeError bool object has no attribute enabled and TypeError bool object is not subscriptable?

- [X] I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

### What happened?

预览Segmentation报错

### Steps to reproduce the problem

1 选择 sam_vit_l
2 上传图片，点好黑点。
3 点击preview Segmentation

### What should have happened?

不报错并且能正常使用

### Commit where the problem happens

webui: 89f9faa6
extension: 0c2d2b7
Python 3.10.10
Mac M1 pro

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Running SAM Inference (504, 416, 3)
SAM inference with 0 box, 2 positive prompts, 1 negative prompts
Creating output image
Traceback (most recent call last):
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/xx/ai/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/xx/ai/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 235, in sam_predict
    return create_mask_output(image_np, masks, boxes_filt), sam_predict_status + (sam_predict_result + "" if install_success else f" However, GroundingDINO installment has failed. Your process automatically fall back to local groundingdino. Check your terminal for more detail and {dino_install_issue_text}.")
UnboundLocalError: local variable 'install_success' referenced before assignment
```

**Comment by nigo81** [comment]
我刚更新插件，也遇到相同的问题
