### ISSUE TITLE
loading it failed after installing the extension from colab

### ISSUE THREAD

**Issue by brianwan19801015** [continue-revolution/sd-webui-segment-anything#112]
Hello All,

Any one encountered the same  issue before?

Error loading script: sam.py
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 20, in <module>
    from scripts.auto import clear_sem_sam_cache, register_auto_sam, semantic_segmentation, sem_sam_garbage_collect, image_layer_internal, categorical_mask_image
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/auto.py", line 12, in <module>
    from modules.paths import extensions_dir
ImportError: cannot import name 'extensions_dir' from 'modules.paths' (/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/paths.py)

**Comment by continue-revolution** [comment]
Most likely you are using a very old webui. I would highly recommend you to update your webui. You may also choose to follow the instruction at https://github.com/continue-revolution/sd-webui-segment-anything/issues/32#issuecomment-1575059063
