### ISSUE TITLE
[Bug]: .DS_Store displayed in SAM Model selection part 

### ISSUE THREAD

**Issue by guozan** [continue-revolution/sd-webui-segment-anything#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the latest version?

- [X] I have updated WebUI and this extension to the latest version

### Do you understand that you should read the 1st item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you understand that you should use the latest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### Do you understand that you should read the 2nd item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you observe problems like AttributeError bool object has no attribute enabled and TypeError bool object is not subscriptable?

- [X] My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

### What happened?

When I opened Segment Anything in SD webui, the SAM Model selection part, displayed ".DS_Store", no matter how I refresh the model, nothing changed; 

I already put sam_vit_h_4b8939.pth inside the folder, and userd several times, it just happended suddenly 

thank you for help 

### Steps to reproduce the problem

1. Segment Anything in SD webui
2. refresh the SAM Model selection part 

### What should have happened?

should display sam_vit_h_4b8939.pth 

### Commit where the problem happens

webui: [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) 
extension: https://github.com/continue-revolution/sd-webui-segment-anything

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no, just using default
```

### Console logs

```Shell
Start SAM Processing
Initializing SAM to mps
Traceback (most recent call last):
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/youben/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/youben/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 201, in sam_predict
    sam = init_sam_model(sam_model_name)
  File "/Users/youben/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 126, in init_sam_model
    sam_model_cache[sam_model_name] = load_sam_model(sam_model_name)
  File "/Users/youben/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 77, in load_sam_model
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
KeyError: ''
```

**Comment by continue-revolution** [comment]
You should not worry about .DS_Store. If the extension can find the model then it is good. You can try removing .DS_Store, or try using another directory to store sam model, which should be ${sd-webui-sam}/models/sam (remember to remove ${sd-webui}/models/sam folder if you choose to use the extension directory to save the model).
