### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Defeng11** [continue-revolution/sd-webui-segment-anything#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the latest version?

- [X] I have updated WebUI and this extension to the latest version

### Do you understand that you should read the 1st item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you understand that you should use the latest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### Do you understand that you should read the 2nd item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you observe problems like AttributeError bool object has no attribute enabled and TypeError bool object is not subscriptable?

- [X] My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

### What happened?

![微信截图_20230620125017](https://github.com/continue-revolution/sd-webui-segment-anything/assets/128026631/d1be7b8b-4a9c-4bf0-ab98-b76c2b1abc1b)

### Steps to reproduce the problem

1.image for Segment Anything
2.Enable GroundingDINO
3.check the box “GroundingDINO_SwinB (938MB)”
4.GroundingDINO Detection Prompt“hair"
5.tick "I want to preview GroundingDINO detection result and select the boxes I want."
6.Generate bounding box
7.tick ”Copy to Inpaint Upload & img2img ControlNet Inpainting“
8.Switch to Inpaint Upload

ControlNet V.1.1.224
1.Unit 0
2.Enable
3.Preprocessor: "inpaint_global_harmonious"
4.Model: "control_v11p_sd15_inpaint [ebff9138]"
5.Preview error

### What should have happened?

NA

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0
extension: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers

call webui.bat
```

### Console logs

```Shell
Start SAM Processing
Using local groundingdino.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinB (938MB)
final text_encoder_type: bert-base-uncased
Initializing SAM to cuda
Running SAM Inference (512, 512, 3)
SAM inference with 1 box, 0 positive prompts, 0 negative prompts
Creating output image
Using local groundingdino.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinB (938MB)
Start SAM Processing
Using local groundingdino.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinB (938MB)
Initializing SAM to cuda
Running SAM Inference (512, 512, 3)
SAM inference with 1 box, 0 positive prompts, 0 negative prompts
Creating output image
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (run_annotator) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [image, checkbox, html, html]
Received outputs:
    [{'value': None, 'visible': True, '__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}]
```

**Comment by Defeng11** [comment]
![214334](https://github.com/continue-revolution/sd-webui-segment-anything/assets/128026631/c63bea3e-69cb-4b0c-b9a5-00d329f8bd10)

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything#single-image

8

**Comment by Defeng11** [comment]
> 

I noticed the instructions for asking questions, and I have checked them before trying again
