### ISSUE TITLE
[Feature]: ${sd-webui-sam}这个是什么文件路径

### ISSUE THREAD

**Issue by thisjam** [continue-revolution/sd-webui-segment-anything#136]
### Expected behavior

下了个 GroundingDINO模型    groundingdino_swint_ogc.pth
不知道放在哪里。

**Comment by continue-revolution** [comment]
${sd-webui-sam} 是插件目录，即webui/extensions/sd-webui-segment-anything

**Comment by thisjam** [comment]
> ${sd-webui-sam} 是插件目录，即webui/extensions/sd-webui-segment-anything
按你说的放 ，点抠图就一直没反应。
那${sd-webui-segment-anything}是什么目录

**Comment by continue-revolution** [comment]
终端报错发一下

**Comment by thisjam** [comment]
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "F:\sd-webu416\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd-webu416\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\sd-webu416\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sd-webu416\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sd-webu416\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\sd-webu416\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\scripts\sam.py", line 200, in sam_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name, install_success)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\scripts\dino.py", line 119, in load_dino_model
    dino = build_model(args)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\local_groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 362, in build_groundingdino
    model = GroundingDINO(
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 97, in __init__
    self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
  File "F:\sd-webu416\extensions\sd-webui-segment-anything\local_groundingdino\util\get_tokenlizer.py", line 19, in get_tokenlizer
    tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
  File "F:\sd-webu416\py310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 659, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "F:\sd-webu416\py310\lib\site-packages\transformers\tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "F:\sd-webu416\py310\lib\site-packages\transformers\tokenization_utils_base.py", line 1831, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "F:\sd-webu416\py310\lib\site-packages\transformers\tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "F:\sd-webu416\py310\lib\site-packages\transformers\models\bert\tokenization_bert.py", line 213, in __init__
    if not os.path.isfile(vocab_file):
  File "genericpath.py", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by thisjam** [comment]
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
要不就卡在这不动了，

**Comment by thisjam** [comment]
> 终端报错发一下

太折磨了，弄了两天没弄好。

**Comment by continue-revolution** [comment]
可能的原因是huggingface被墙，无法下载tokenizer。你可以试试终端配置代理。

**Comment by thisjam** [comment]
> 可能的原因是huggingface被墙，无法下载tokenizer。你可以试试终端配置代理。

终端代理不会搞，我vpn开的全局代理模式，平时没什么问题啊。哎，不弄了，累人。

**Comment by Fatal-Eror** [comment]
> > 可能的原因是huggingface被墙，无法下载tokenizer。你可以试试终端配置代理。
> 
> 终端代理不会搞，我vpn开的全局代理模式，平时没什么问题啊。哎，不弄了，累人。

我也遇到同样问题了，在隔壁问了作者大佬后解决了。就是终端代理问题，开了梯子貌似秋叶包的终端还是没翻墙的，得去秋叶终端那里配置代理，大佬还说有些东西自己没法手动下所以单独下载两个模型放文件夹也没法用，还是得靠终端自己下。你可以参考一下https://github.com/continue-revolution/sd-webui-segment-anything/issues/138
