### ISSUE TITLE
网络问题无法使用groundingDINO，下载本地模型后依然无法使用

### ISSUE THREAD

**Issue by Fatal-Eror** [continue-revolution/sd-webui-segment-anything#138]
我使用的是windows的秋叶包v4.2
1.根据这个视频内容，https://www.bilibili.com/video/BV1Vh411F7Zn/?spm_id_from=333.337.search-card.all.click&vd_source=5fdf8441f38454739cb347f940e766c2，先是尝试了不勾选bypass c++ problem的配置，配置完成后点击generate bounding box，会显示time out或者远程主机关闭了链接之类的问题， 下载模型并放置在

**Comment by continue-revolution** [comment]
huggingface被墙了，你终端没办法下载Bert的tokenizer

终端代理有它自己的配法

**Comment by Fatal-Eror** [comment]
> huggingface被墙了，你终端没办法下载Bert的tokenizer
> 
> 终端代理有它自己的配法

那自己手动下载的两个模型文件要怎么样才能让他用上呢，直接塞到插件的model里他好像没检测到，还是会去抱脸继续下载

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything#groundingdino

**Comment by continue-revolution** [comment]
位置放错了可能

**Comment by Fatal-Eror** [comment]
> 位置放错了可能

我放的位置是sd-webui-aki-v4.2\extensions\sd-webui-segment-anything\models\grounding-dino，应该是和他说的位置一样吧

**Comment by continue-revolution** [comment]
你下载的groundingdino模型并不是bert的tokenizer，tokenizer是另外的东西，是用来识别你文字的东西。

这个tokenizer目前只能通过终端自动下载，你需要配置终端代理，即http_proxy和https_proxy。因为huggingface代码库诡异的下载逻辑，我尚不知道如何直接下载然后放到某个文件夹。可能会在下下一个版本再尝试解决这个问题。

**Comment by Fatal-Eror** [comment]
> 你下载的groundingdino模型并不是bert的tokenizer，tokenizer是另外的东西，是用来识别你文字的东西。
> 
> 这个tokenizer目前只能通过终端自动下载，你需要配置终端代理，即http_proxy和https_proxy。因为huggingface代码库诡异的下载逻辑，我尚不知道如何直接下载然后放到某个文件夹。可能会在下下一个版本再尝试解决这个问题。

感谢大佬指路，目前问题已经解决，确实就是终端代理不行。解决方法是：
1. 开启clash梯子
2. windows自己的设置-网络和internet-代理，关闭自动检测设置，手动代理设置-使用代理服务器设置为开，并复制代理ip和端口号，例如我这里是http://127.0.0.1:7890（不同人最后四位可能不一样）
3. 随便谷歌一下确定浏览器是能翻墙出去的
4. 秋叶包左边最底下的设置-一般设置-网络设置-代理设置-代理服务器地址填上上面的ip，我这里是http://127.0.0.1:7890，把下面所有将代理应用到xxx全部开启
5. 重新打开webui，点击generate bounding box成功开始下载两个模型，并识别内容

插件效果很棒，尝试识别人头和衣服之类的都非常不错，衷心感谢大佬的制作。

**Comment by Fatal-Eror** [comment]
Have solved problem, the error is caused by terminal proxy.
1. use clash
2. windows settings-Network & internet-proxy, close auto setting, and use proxy server. Then i copy down the ip and port http://127.0.0.1:7890 (the last four digits might be different for different people).
3. set terminal proxy, my webui launcher has a place to fill in the proxy configuration, and i copy http://127.0.0.1:7890 into it. If your launcher is different from mine, you can try to fix this internet problem with other terminal proxy tutorial, here is one teaching how to config the cmd, git, and powershell, https://sleepyocean.github.io/pages/da27da/#windows%E5%91%BD%E4%BB%A4 , the content is chinese but i think it can be translated by browser.
4. open webui, click "generate bounding box", the terminal successfully download model from huggingface.

**Comment by continue-revolution** [comment]
Note to English speakers: the above method only works for people who
1. are using package from Akegarasu
2. are blocked from accessing huggingface due to whatever reason.

This issue will be closed once I find a way to completely bypass downloading huggingface material from terminal.

**Comment by openwaterer** [comment]
> 你下载的groundingdino模型并不是bert的tokenizer，tokenizer是另外的东西，是用来识别你文字的东西。
> 
> 这个tokenizer目前只能通过终端自动下载，你需要配置终端代理，即http_proxy和https_proxy。因为huggingface代码库诡异的下载逻辑，我尚不知道如何直接下载然后放到某个文件夹。可能会在下下一个版本再尝试解决这个问题。

那完蛋了 我用的国内云服务器，是墙不出来的。它一定要连到huggingface下载吗，我把上面这位成功的groundingdino文件夹复制过来用行不行

**Comment by continue-revolution** [comment]
@openwater 有的云服务器提供学术加速服务，例如autodl，建议优先使用提供学术加速服务的云服务器。他会把bert下载到你不知道的位置，复制他的文件夹无法陈工成功。

**Comment by openwaterer** [comment]
> @openwaterer 有的云服务器提供学术加速服务，例如autodl，建议优先使用提供学术加速服务的云服务器。他会把bert下载到你不知道的位置，复制他的文件夹无法解决问题。

老哥 那我准备整个海外服务器，安装好后整个服务器文件镜像回国内服务器，这样可行吗。它总不会甚至都不在WebUI文件夹里面吧

**Comment by continue-revolution** [comment]
@openwaterer 极有可能不在webui文件夹，它会在你的HF_HOME这个环境变量指向的文件夹里，如果HF_HOME为空，就会下载到~/.cache/hub （或者是类似的地方）

**Comment by wibur0620** [comment]
没用整合包的怎么解决啊

**Comment by Fatal-Eror** [comment]
> 没用整合包的怎么解决啊

你可以参考这个链接里的终端代理设置，里面有提及如何配置cmd，git和powershell的终端代理：https://sleepyocean.github.io/pages/da27da/

**Comment by zyjssf** [comment]
> > 你下载的接地恐龙模型不是伯特的分词器，分词器是另外的东西，是用来识别你文字的东西。
> > tokenizer目前只能通过终端自动下载这个，你需要配置终端代理，即http_proxy和https_proxy。因为huggingface代码库诡异的下载逻辑，我尚异不知道如何直接下载然后放到某个文件夹。可能会在下下一个版本再尝试解决这个问题。
> 
> 那完了我用国内的云服务器，是墙不出来的。它一定要连到huggingface下载吗，我把上面这个成功的groundingdino文件夹复制过来用行不行

现在遇到和你一样的问题了，直接复制文件进去没用，云服务器又不能翻墙，请问下这个问题解决了吗？

**Comment by wangxihao** [comment]
> > > 你下载的接地恐龙模型不是伯特的分词器，分词器是另外的东西，是用来识别你文字的东西。
> > > tokenizer目前只能通过终端自动下载这个，你需要配置终端代理，即http_proxy和https_proxy。因为huggingface代码库诡异的下载逻辑，我尚异不知道如何直接下载然后放到某个文件夹。可能会在下下一个版本再尝试解决这个问题。
> > 
> > 
> > 那完了我用国内的云服务器，是墙不出来的。它一定要连到huggingface下载吗，我把上面这个成功的groundingdino文件夹复制过来用行不行
> 
> 现在遇到和你一样的问题了，直接复制文件进去没用，云服务器又不能翻墙，请问下这个问题解决了吗？

复制过来是可以用的， models--bert-base-uncased文件夹放在~/.cache/huggingface/hub下

**Comment by 6666665** [comment]
I have solved this problem.
You need to start from [https://huggingface.co/bert-base-uncased/tree/main](url) Download files to `/Home/ubuntu/table differentiation webui/bert base uncased` (create this folder if it does not exist)

**Comment by luchec** [comment]
我更惨，用的是秋叶4.4的，setment anything装了，groundingdino的pth下载了，也放到\models\grounding-dino\下了，然后那个huggingface的文件也自动下好了在\sd-webui-aki-v4.4\.cache\sdwebuilauncher\hfmirror\blob\ 里，结果一点预览，就直接爆错了。
完全无解

Using local groundingdino.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\StableDiffusion\sd-webui-aki-v4.4\python\lib\site-packages\transformers\modeling_utils.py", line 463, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\StableDiffusion\sd-webui-aki-v4.4\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "D:\StableDiffusion\sd-webui-aki-v4.4\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\StableDiffusion\sd-webui-aki-v4.4\python\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\StableDiffusion\sd-webui-aki-v4.4\python\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xf0'.

During handling of the above exception, another exception occurred:

。。。。。。



from a TF 2.0 checkpoint, please set from_tf=True.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by KINGSTON-115** [comment]
@Fatal-Eror 十分感谢大佬，相同的问题按照大佬的操作顺利解决了!!!
Thank you very much!!!

**Comment by KINGSTON-115** [comment]
Done. However, GroundingDINO installment has failed. Your process automatically fall back to local groundingdino. See your terminal for more detail and permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
如上报错，虽然改设置之后能从终端直接下groundingDino，但是下完后还是有这样的报错，我高兴早了 @Fatal-Eror

**Comment by jackyjinjing** [comment]
huggingface network connect problem in cloud server can refer to this pr : https://github.com/IDEA-Research/Grounded-Segment-Anything/pull/517
which has bean merged
