### ISSUE TITLE
运行webui时报错

### ISSUE THREAD

**Issue by AoyamaT1** [continue-revolution/sd-webui-segment-anything#24]
Error loading script: sam.py Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 15, in <module> from segment_anything import SamPredictor, sam_model_registry ModuleNotFoundError: No module named 'segment_anything'

根据错误信息说没有明为 'segment_anything'的模型，但该模型不是叫sam_vit_h_4b8939.pth，为什么会有这个报错呢？进去webui后并没有seganything区域

**Comment by AoyamaT1** [comment]
好的谢谢，后面去试试

**Comment by AoyamaT1** [comment]
好的谢谢，后面去试试
