### ISSUE TITLE
[Bug]: No module named groundingdino

### ISSUE THREAD

**Issue by Matti-Koopa** [continue-revolution/sd-webui-segment-anything#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### What happened?

Startup of webui does produce this error:
```
ModuleNotFoundError: No module named 'groundingdino'
```
The README doesn't say anything about needing to nave it installed. It says groundingdino is optional. If it's required, it should be automatically installed with requirements.txt or some other way.

### Steps to reproduce the problem

start webui

### What should have happened?

no error

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
extension: b8f3c09a2116ca4e5e5cd6c1a1133116f2428271

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--api --disable-safe-unpickle --no-half-vae
```

### Console logs

```Shell
No module 'xformers'. Proceeding without it.
Error loading script: dino.py
Traceback (most recent call last):
  File "K:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 12, in <module>
    import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino'

Error loading script: sam.py
Traceback (most recent call last):
  File "K:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 18, in <module>
    from scripts.dino import dino_model_list, dino_predict_internal, show_boxes, clear_dino_cache
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 12, in <module>
    import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino'
```

### Additional information

Windows 10, not on WSL

**Comment by continue-revolution** [comment]
groundingdino is required. Can it be installed automatically? I think it can. If it cannot, please paste here the beginning of the log when you start webui. It may contain why groundingdino cannot be properly installed.

**Comment by Matti-Koopa** [comment]
```
Requirement already satisfied: matplotlib in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from supervision==0.4.0->groundingdino==0.1.0) (3.6.2)
Requirement already satisfied: typing-extensions in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from torch->groundingdino==0.1.0) (4.4.0)
Requirement already satisfied: requests in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (2.25.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (9.4.0)
Requirement already satisfied: regex!=2019.12.17 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (2022.10.31)
Requirement already satisfied: tqdm>=4.27 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (4.64.1)
Requirement already satisfied: packaging>=20.0 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (21.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.13.4)
Requirement already satisfied: pyyaml>=5.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (6.0)
Requirement already satisfied: filelock in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (3.8.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (1.0.6)
Requirement already satisfied: kiwisolver>=1.0.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->supervision==0.4.0->groundingdino==0.1.0) (4.38.0)
Requirement already satisfied: colorama in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.27->transformers->groundingdino==0.1.0) (0.4.6)
Requirement already satisfied: certifi>=2017.4.17 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2022.9.24)
Requirement already satisfied: chardet<5,>=3.0.2 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.13)
Requirement already satisfied: six>=1.5 in k:\ai\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->supervision==0.4.0->groundingdino==0.1.0) (1.16.0)
Building wheels for collected packages: groundingdino, pycocotools
  Building wheel for groundingdino (setup.py): started
  Building wheel for groundingdino (setup.py): finished with status 'error'
  Running setup.py clean for groundingdino
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
Failed to build groundingdino pycocotools

stderr: WARNING: Ignoring invalid distribution -rotobuf (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ransformers (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ransformers (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
  Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Matti-Koopa\AppData\Local\Temp\pip-req-build-w1xjnz5u'
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [49 lines of output]
  Building wheel groundingdino-0.1.0
  Compiling with CUDA
  running bdist_wheel
  K:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\version.py -> build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino
  creating build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\transforms.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  creating build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\registry.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  creating build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\box_ops.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\get_tokenlizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\inference.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\logger.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\misc.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slconfig.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slio.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\time_counter.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\visualizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\vl_utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\bertwarper.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\fuse_modules.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\groundingdino.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\ms_deform_attn.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer_vanilla.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\backbone.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\position_encoding.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\swin_transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  running build_ext
  K:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  error: [WinError 2] Das System kann die angegebene Datei nicht finden
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for groundingdino
  error: subprocess-exited-with-error

  Building wheel for pycocotools (pyproject.toml) did not run successfully.
  exit code: 1

  [23 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
  C:\Users\Matti-Koopa\AppData\Local\Temp\pip-build-env-3k_6pn0h\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Matti-Koopa\AppData\Local\Temp\pip-install-ud30h47b\pycocotools_3dbad7439f824b5982f2e0a4b310d056\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-cpython-310
  creating build\temp.win-amd64-cpython-310\Release
  creating build\temp.win-amd64-cpython-310\Release\common
  creating build\temp.win-amd64-cpython-310\Release\pycocotools
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Matti-Koopa\AppData\Local\Temp\pip-build-env-3k_6pn0h\overlay\Lib\site-packages\numpy\core\include -I./common -IK:\AI\stable-diffusion-webui\venv\include -IC:\Users\Matti-Koopa\AppData\Local\Programs\Python\Python310\include -IC:\Users\Matti-Koopa\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-cpython-310\Release\./common/maskApi.obj
  maskApi.c
  ./common/maskApi.c(8): fatal error C1083: Datei (Include) kann nicht geffnet werden: "math.h": No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
WARNING: Ignoring invalid distribution -rotobuf (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ransformers (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ransformers (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (k:\ai\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ransformers (k:\ai\stable-diffusion-webui\venv\lib\site-packages)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: K:\AI\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip




Launching Web UI with arguments: --api --disable-safe-unpickle --no-half-vae --xformers
Error loading script: dino.py
Traceback (most recent call last):
  File "K:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 12, in <module>
    import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino'

Error loading script: sam.py
Traceback (most recent call last):
  File "K:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 18, in <module>
    from scripts.dino import dino_model_list, dino_predict_internal, show_boxes, clear_dino_cache
  File "K:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 12, in <module>
    import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino'

Loading weights [812cd9f9d9] from K:\AI\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.ckpt
Creating model from config: K:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights found near the checkpoint: K:\AI\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 5.9s (load weights from disk: 0.9s, create model: 0.6s, apply weights to model: 0.7s, apply half(): 0.9s, load VAE: 0.7s, move model to device: 1.0s, load textual inversion embeddings: 1.2s).
[VRAMEstimator] Loaded benchmark data.
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Startup time: 18.3s (import torch: 4.7s, import gradio: 1.3s, import ldm: 0.6s, other imports: 1.3s, load scripts: 1.9s, load SD checkpoint: 6.1s, create ui: 2.0s, gradio launch: 0.1s, scripts app_started_callback: 0.2s).
```

**Comment by continue-revolution** [comment]
It seems that your device cannot compile some C++. I will look into this. Perhaps you should run `git checkout 99a0fe5` on your terminal to revert back to the previous version.

**Comment by continue-revolution** [comment]
update: I have reverted to a previous commit. After I find a good solution I will update.

**Comment by SlongLiu** [comment]
It seems like the problem is caused by the pycocotools, which does not support Windows well.

Here are some suggestions: https://changhsinlee.com/pycocotools/

**Comment by SlongLiu** [comment]
try add one line to include the GroundingDINO folder to the environment variables: 

```python
sys.path.append(os.path.join(os.getcwd(), "GroundingDINO"))
```

**Comment by xam0482** [comment]
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.

**Comment by continue-revolution** [comment]
> The detected CUDA version (12.1) mismatches the version that was used to compile PyTorch (11.8). Please make sure to use the same CUDA versions.

download cuda 11.8 from nvidia should help

**Comment by xam0482** [comment]
> > 检测到的 CUDA 版本 (12.1) 与用于编译 PyTorch (11.8) 的版本不匹配。请确保使用相同的 CUDA 版本。
> 
> 从 nvidia 下载 cuda 11.8 应该有帮助

我已经解决了 单独下载源码编译 cuda11.8 能运行
上面的问题可能来自于 无法下载正确的版本造成的，我也是同样的提示。
解决这个问题的过程 还发现了一个历史问题的解决方法
就是cuda12.1 不用降级安装cuda11.8就可以编译的方法
 把cuda11.8目录命 改成cuda12.1  然后编译，之后再改回来，还不用重启

**Comment by xam0482** [comment]
不是所有 pip的源镜像 都有 GroundingDINO
阿里的有 另外清华那几个没有

**Comment by continue-revolution** [comment]
> 不是所有 pip的源镜像 都有 GroundingDINO 阿里的有 另外清华那几个没有

现在可以直接pip install groundingdino了吗，我写插件的时候还不行。

**Comment by xam0482** [comment]
> 

我是单独下载github 源码编译的，用阿里的 pip 提示没有正确版本

**Comment by continue-revolution** [comment]
> > 
> 
> 我是单独下载github 源码编译的，用阿里的 pip 提示没有正确版本

那可能还不行，那现在的从github下载源码编译的设置恐怕还得保留

**Comment by xam0482** [comment]
挺多pip 源镜像没有，刚才我挨个源地址里翻了

**Comment by continue-revolution** [comment]
> 挺多pip 源镜像没有，刚才我挨个源地址里翻了

应该是连官方源都没有，只能自己下源码自己编译

**Comment by xam0482** [comment]
之前用的是 pytorch2.1 night 版 因 cuda12.1 不能编译xformers 不得已放弃了 ，换回了2.0 cuda118 
另外 凌晨 第一次试用GroundingDINO  结果后台在 生成图片时又死锁了， 3070ti 8g 估计碎片显存耗光了

**Comment by wangfeng-1** [comment]
windows安装 vs_BuildTools ，https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/

**Comment by cdmusic2019** [comment]
> 



> > > 检测到的 CUDA 版本 (12.1) 与用于编译 PyTorch (11.8) 的版本不匹配。请确保使用相同的 CUDA 版本。
> > 
> > 
> > 从 nvidia 下载 cuda 11.8 应该有帮助
> 
> 我已经解决了 单独下载源码编译 cuda11.8 能运行 上面的问题可能来自于 无法下载正确的版本造成的，我也是同样的提示。 解决这个问题的过程 还发现了一个历史问题的解决方法 就是cuda12.1 不用降级安装cuda11.8就可以编译的方法 把cuda11.8目录命 改成cuda12.1 然后编译，之后再改回来，还不用重启

我也犯过这个错，不是最新就是最好。但可以把12.1安装的文件手动删除，再安装11.7或11.8的。

**Comment by xam0482** [comment]
> 我也犯过这个错，不是最新就是最好。但可以把12.1安装的文件手动删除，再安装11.7或11.8的。

不需要删除，不不需要重装，
秘密在于 系统变量  CUDA_PATH    如果直接修改 需要重启
简单的方式是  
已经按了 12.1的  不用卸载 继续装 V11.8
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA
这个目录下就会有多个目录
V11.7
V11.8
V12.1
正常 会使用   系统变量下的 CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1

关键来了
只要把  V12.1的文件夹该成别的名字 ，接着把底版本的  V11.8文件夹名 改成 V12.1   来个偷梁换柱  ，解释器 就能认为是 V11.8

这时就可以编译了  使用的就V11.8  
编译完了 ，有必要的话，就把文件夹的名字该回来 继续使用V12.1 版本呢

**Comment by sdbds** [comment]
折腾半天终于能用了...
因为读取不到Windows kits下面的编译文件，复制过来就好了。

**Comment by g558800** [comment]
> > 我也犯过这个错，不是最新就是最好。但可以把12.1安装的文件手动删除，再安装11.7或11.8的。
> 
> 不需要删除，不不需要重装， 秘密在于 系统变量 CUDA_PATH 如果直接修改 需要重启 简单的方式是 已经按了 12.1的 不用卸载 继续装 V11.8 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA 这个目录下就会有多个目录 V11.7 V11.8 V12.1 正常 会使用 系统变量下的 CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
> 
> 关键来了 只要把 V12.1的文件夹该成别的名字 ，接着把底版本的 V11.8文件夹名 改成 V12.1 来个偷梁换柱 ，解释器 就能认为是 V11.8
> 
> 这时就可以编译了 使用的就V11.8 编译完了 ，有必要的话，就把文件夹的名字该回来 继续使用V12.1 版本呢

请问需要安装vc++buildtools吗？

**Comment by xam0482** [comment]
> 请问需要安装vc++buildtools吗？

需要，编译工具 还是必须要有的

**Comment by g558800** [comment]
> > 请问需要安装vc++buildtools吗？
> 
> 需要，编译工具 还是必须要有的

非常感谢！

**Comment by g558800** [comment]
我安装了vc++buildtools和cudatoolkit11.8后，还是会出现NameError: name '_C' is not defined

**Comment by ALANXIAORUI** [comment]
No module named 'groundingdino.datasets'

**Comment by g558800** [comment]
> No module named 'groundingdino.datasets'

![image](https://user-images.githubusercontent.com/119348639/235294220-2092216a-13b0-464d-887e-2d2d1967c285.png)

**Comment by xam0482** [comment]
> 

最好是手动编译，我还记得buildtools 版本不能太高 要在2019之前的

**Comment by cdmusic2019** [comment]
c++ https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/

**Comment by ALANXIAORUI** [comment]
> > No module named 'groundingdino.datasets'
> 
> ![image](https://user-images.githubusercontent.com/119348639/235294220-2092216a-13b0-464d-887e-2d2d1967c285.png)

不是太理解，这个grounded anything也要自己手动装吗，我是直接装了groundingdino

**Comment by cdmusic2019** [comment]
不需要手动安装，作者提供的安装连接已经包括了， 但需要自行下载 groundingdino的模型包，有两个，一个600多M，一个900多M，根据个人配置选其一，放在插件目录中 “extensions\sd-webui-segment-anything\models\grounding-dino” 里面，

**Comment by g558800** [comment]
> c++ https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/ ,勾选 用于 Windows 的 C++ CMake 工具 适用于v142生成工具(14.29-16.11)的C++/CLI支持 这两项。

怪不得，我是有多新就装了多新的进去。

**Comment by g558800** [comment]
> > > No module named 'groundingdino.datasets'
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/119348639/235294220-2092216a-13b0-464d-887e-2d2d1967c285.png)
> 
> 不是太理解，这个grounded anything也要自己手动装吗，我是直接装了groundingdino

我当时也是缺少这个，把图上那个dataset直接复制去相应位置，再使用就不再提示这个错误了。

**Comment by Chenjm08** [comment]
我的stable diffusion是用docker 部署的，在Dockerfile中 `pip install groundingdino`，会报_C没有定义的错误。然后使用Dockerfile下载源码，进入目录，使用 `pip install -e . `进行安装，还是报_C没有定义的错误。但是在docker 容器中使用 `pip install -e .` 是可以解决_C没有定义的错误，只是不知道为什么在Dockerfile中使用`pip install -e .`不起作用。

查看了groundingdino 路径，如果生成_C.cpython-310-x86_64-linux-gnu.so 就对了，没有生成则错误。

<img width="669" alt="image" src="https://github.com/continue-revolution/sd-webui-segment-anything/assets/4150639/eb0f813c-fa25-4a53-8063-75f378cdc2b0">

**Comment by chenxqiyu** [comment]
> No module named 'groundingdino.datasets'

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/10222853/2c759931-3baf-4360-a5f4-f1b3c5725fc0)
克隆https://github.com/IDEA-Research/GroundingDINO的把复制groundingdino文件夹放到插件根目录即可
