### ISSUE TITLE
小白疑惑，为什么没有这个模块呢 amd用户

### ISSUE THREAD

**Issue by sorryhorizonTT** [continue-revolution/sd-webui-segment-anything#43]
Python 版本 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash值: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39

本整合包由 NovelAI 中文频道 出品，严禁倒卖

正在启动 WebUI 中...

Web UI 运行参数为: --autolaunch --no-half --precision full --opt-sub-quad-attention
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper-main\setting.json
Error loading script: api.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\api.py", line 9, in <module>
    from scripts.sam import init_sam_model, dilate_mask, sam_predict, sam_model_list
  File "D:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 17, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Error loading script: sam.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 17, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

SD-Webui API layer loaded

**Comment by continue-revolution** [comment]
你最好是先更新你的webui然后再试试。可能是你的镜像有问题，至少清华镜像有这个包。
