### ISSUE TITLE
这是什么错误？

### ISSUE THREAD

**Issue by sorryhorizonTT** [continue-revolution/sd-webui-segment-anything#44]
Traceback (most recent call last):
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\extensions\sd-webui-segment-anything\scripts\sam.py", line 187, in sam_predict
    masks, _, _ = predictor.predict(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\segment_anything\predictor.py", line 154, in predict
    masks, iou_predictions, low_res_masks = self.predict_torch(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\segment_anything\predictor.py", line 222, in predict_torch
    sparse_embeddings, dense_embeddings = self.model.prompt_encoder(
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 155, in forward
    point_embeddings = self._embed_points(coords, labels, pad=(boxes is None))
  File "D:\SD2.2b(简中)+DirectML3.14+CN1.1整合包\python\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 85, in _embed_points
    labels = torch.cat([labels, padding_label], dim=1)
RuntimeError

**Comment by continue-revolution** [comment]
多个box+多个image会报这种错，但是这种应该已经被我disable掉了。你得把你的详细参数发给我（至少得发你的插件参数截图）我才能找到问题。

**Comment by continue-revolution** [comment]
多个box+多个image会报这种错，但是这种应该已经被我disable掉了。你得把你的详细参数发给我（至少得发你的插件参数截图）我才能找到问题。

**Comment by sorryhorizonTT** [comment]
![image](https://user-images.githubusercontent.com/130207576/232840063-e9d2c0da-91f4-401a-8413-8833778ae4bc.png)

**Comment by sorryhorizonTT** [comment]
我不太清楚 应该都是默认 我没调过

**Comment by continue-revolution** [comment]
点击图片加点才能操作。

**Comment by sorryhorizonTT** [comment]
是的 我点了

**Comment by continue-revolution** [comment]
你点了之后图片上有点吗，我看你的截图里面似乎没有。你可以F12看看浏览器console.
而且这不正常，我现在的版本如果没有点的话根本就不会过到这一步，试一下更新插件看看ui输出是啥。

**Comment by sorryhorizonTT** [comment]
我应该怎么看
![image](https://user-images.githubusercontent.com/130207576/232957952-19436e40-3c7a-4633-8076-db644ce731f7.png)

**Comment by continue-revolution** [comment]
更新webui版本，你这个太老了

**Comment by continue-revolution** [comment]
而且你这个torch只有cpu，没下对

**Comment by cdmusic2019** [comment]
不要玩整合版。

**Comment by sorryhorizonTT** [comment]
我如果用的N卡我也不用整合版了qwq

**Comment by continue-revolution** [comment]
自己租个N卡吧。你用纯cpu跑图体验很糟糕的
