### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Arron17** [continue-revolution/sd-webui-segment-anything#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### What happened?

When following the instructions for ControlNet Inpainting:

> ControlNet Inpainting
>
>   Check Copy to ControlNet Inpaint and select the ControlNet panel for inpainting if you want to use multi-ControlNet. You can >be either at img2img tab or at txt2img tab to use this functionality.
>    Configurate ControlNet panel. Click Enable, preprocessor choose inpaint_global_harmonious, model choose >control_v11p_sd15_inpaint [ebff9138]. There is no need to upload image to the ControlNet inpainting panel, as SAM extension will >help you to do that. Write your prompts, configurate A1111 panel and click Generate.

When using Txt2Img get a message to say there is no image input:
`Error running process: D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 779, in process
    raise ValueError('controlnet is enabled but no input image is given')
ValueError: controlnet is enabled but no input image is given`

If I follow the same steps in Img2Img a different error appears, however it does seem to actually generate the image correctly.
Error in Img2Img is:
`Error running process: D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in process
    detected_map, is_image = preprocessor(input_image, res=unit.processor_res, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 57, in inpaint
    mask = resize_image(img[:, :, 3:4], res)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\util.py", line 33, in resize_image
    img = cv2.resize(input_image, (W, H), interpolation=cv2.INTER_LANCZOS4 if k > 1 else cv2.INTER_AREA)
cv2.error: Unknown C++ exception from OpenCV code`

### Steps to reproduce the problem

Included images of my settings:

![image](https://user-images.githubusercontent.com/87210034/232615949-05950dbc-d029-4cac-a050-31587f486576.png)
![image](https://user-images.githubusercontent.com/87210034/232615994-faf0cd90-14ce-4eef-9abe-65b127bc690d.png)
![image](https://user-images.githubusercontent.com/87210034/232616030-8e2baaf8-aa9a-4f39-99ae-5b4d62b16efa.png)
![image](https://user-images.githubusercontent.com/87210034/232616080-c92b2780-de84-438f-8819-9a42838208d5.png)

### What should have happened?

The instructions state that I do not need to put an image into the ControlNet area as the extension will handle that. However it is giving an error saying there is no input image.

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
extension: 4ee968b5a375e2c69e5769ed5c11bb18fa6e65f0

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --opt-channelslast
```

### Console logs

```Shell
Included in the error message above
```

**Comment by continue-revolution** [comment]
You should update the ControlNet extension to the most updated version. I created a pull request to ControlNet extension several hours ago to support this functionality. For img2img, I will test and update here.

**Comment by Arron17** [comment]
> You should update the ControlNet extension to the most updated version. I created a pull request to ControlNet extension several hours ago to support this functionality. For img2img, I will test and update here.
> 
> Edit: img2img works well on my side. You should update ControlNet extension.

I have no further updates for the ControlNet Extension, there was an update for Segment Anything which I updated. Issue is still present.

**Comment by continue-revolution** [comment]
please go to `Extensions` panel and check your controlnet version. if it is one of 
![image](https://user-images.githubusercontent.com/63914308/232626718-bdfe272c-6efd-4a02-a54c-4ba2deec749e.png)
then it might be my problem. But I cannot reproduce your error. I think your UI setting is OK.

**Comment by Arron17** [comment]
> please go to `Extensions` panel and check your controlnet version. if it is one of ![image](https://user-images.githubusercontent.com/63914308/232626718-bdfe272c-6efd-4a02-a54c-4ba2deec749e.png) then it might be my problem. But I cannot reproduce your error. I think your UI setting is OK.

sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	4cfa8aa7 (Mon Apr 17 20:04:26 2023)
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything.git	63d66389 (Mon Apr 17 22:32:41 2023)

**Comment by continue-revolution** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/736#issuecomment-1512188769

I will try to reproduce your error on my end, but it's hard for me to understand the reason.

**Comment by Arron17** [comment]
> [Mikubill/sd-webui-controlnet#736 (comment)](https://github.com/Mikubill/sd-webui-controlnet/issues/736#issuecomment-1512188769)
> 
> I will try to reproduce your error on my end, but it's hard for me to understand the reason.

Here is a video of what I'm doing for Txt2Img - https://streamable.com/s23pfe

**Comment by continue-revolution** [comment]
ok I understand. You should manually allow other scripts to control ControlNet extension. Some extension, such as posex, internally bypassed this requirement, but I don't think it is a good practice. Go to settings->controlnet->Allow other script to control this extension

**Comment by continue-revolution** [comment]
yes. I just updated my README and bug report checkbox to reflect this.
