### ISSUE TITLE
ERROR:can't use the extension

### ISSUE THREAD

**Issue by GoldenDog1218** [continue-revolution/sd-webui-segment-anything#56]
sd version:226d840
Error loading script: api.py
Traceback (most recent call last):
  File "Y:\stable-diffusion-webui_23-03-10\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "Y:\stable-diffusion-webui_23-03-10\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Y:\stable-diffusion-webui_23-03-10\extensions\sd-webui-segment-anything\scripts\api.py", line 9, in <module>
    from scripts.sam import init_sam_model, dilate_mask, sam_predict, sam_model_list
  File "Y:\stable-diffusion-webui_23-03-10\extensions\sd-webui-segment-anything\scripts\sam.py", line 17, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Error loading script: sam.py
Traceback (most recent call last):
  File "Y:\stable-diffusion-webui_23-03-10\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "Y:\stable-diffusion-webui_23-03-10\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Y:\stable-diffusion-webui_23-03-10\extensions\sd-webui-segment-anything\scripts\sam.py", line 17, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

**Comment by continue-revolution** [comment]
This can happen because your Python mirror does not have segment_anything. Please ‘pip install segment_anything’ manually. Remember to install to your UI environment
