### ISSUE TITLE
Error loading script: api.py

### ISSUE THREAD

**Issue by flypigzju** [continue-revolution/sd-webui-segment-anything#65]
segment_anything already installed from pip

Get error when launching webui

_Error loading script: api.py
Traceback (most recent call last):
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\api.py", line 9, in <module>
    from scripts.sam import init_sam_model, dilate_mask, sam_predict, sam_model_list
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 20, in <module>
    from scripts.auto import clear_sem_sam_cache, register_auto_sam, semantic_segmentation, sem_sam_garbage_collect, image_layer_internal, categorical_mask_image
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\auto.py", line 11, in <module>
    from modules.paths import extensions_dir
ImportError: cannot import name 'extensions_dir' from 'modules.paths' (D:\AI\StableDiffusion\stable-diffusion-webui\modules\paths.py)

Error loading script: auto.py
Traceback (most recent call last):
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\auto.py", line 11, in <module>
    from modules.paths import extensions_dir
ImportError: cannot import name 'extensions_dir' from 'modules.paths' (D:\AI\StableDiffusion\stable-diffusion-webui\modules\paths.py)

Error loading script: sam.py
Traceback (most recent call last):
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 20, in <module>
    from scripts.auto import clear_sem_sam_cache, register_auto_sam, semantic_segmentation, sem_sam_garbage_collect, image_layer_internal, categorical_mask_image
  File "D:\AI\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\auto.py", line 11, in <module>
    from modules.paths import extensions_dir
ImportError: cannot import name 'extensions_dir' from 'modules.paths' (D:\AI\StableDiffusion\stable-diffusion-webui\modules\paths.py)_

**Comment by continue-revolution** [comment]
Update your webui should resolve this problem.
