### ISSUE TITLE
新版本update Mask报错

### ISSUE THREAD

**Issue by lurenchou** [continue-revolution/sd-webui-segment-anything#70]
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Dilation Amount:  18
Traceback (most recent call last):
  File "C:\novelai-webui-aki\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\novelai-webui-aki\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\novelai-webui-aki\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\novelai-webui-aki\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\novelai-webui-aki\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\novelai-webui-aki\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\novelai-webui-aki\extensions\sd-webui-segment-anything\scripts\sam.py", line 63, in update_mask
    binary_img = np.array(mask_image.convert('1'))
AttributeError: 'list' object has no attribute 'convert'

**Comment by g558800** [comment]
me too

**Comment by continue-revolution** [comment]
改了，看看好了没

**Comment by lurenchou** [comment]
可以了，完美
