### ISSUE TITLE
显存不足

### ISSUE THREAD

**Issue by 3077107162** [continue-revolution/sd-webui-segment-anything#78]
使用插件的时候报显存不足的错误，即使把图片压缩到256x256还是提示显存不足。但是，自己本地部署的sam的工程，即使超过1000的分辨率，都可以运行，不会出现显存的问题。
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 8.00 GiB total capacity; 7.19 GiB already allocated; 0 bytes free; 7.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by continue-revolution** [comment]
最大的模型就得要7G，你可以用小模型

**Comment by daizhuo** [comment]
我也是 8 G 的显存，第一次运行成功，然后就一直不行了，奇怪喔。烦请作者查找下原因，如果一定要大于 8G 显存才能用，这个要求就有点高了，还存在优化的空间。谢谢！

**Comment by 3077107162** [comment]
> 最大的模型就得要7G，你可以用小模型

奇怪，换了小模型确实可以跑了。但是直接部署的sam，即使最大的h模型也是可以运行的，是不是插件里面做了其他的操作，导致占用了更多的显存。

**Comment by daizhuo** [comment]
请问换了小模型是什么意思？我已经换了最小那个300多M的SAM模型，仍然是不行啊。

**Comment by 3077107162** [comment]
> 请问换了小模型是什么意思？我已经换了最小那个300多M的SAM模型，仍然是不行啊。
换了l模型就可以跑了，理论上来说你的应该也可以，不应该最小的模型还是跑不了，你看看是不是显存没清掉，重启试一下。

**Comment by daizhuo** [comment]
这是我的 CMD 显示的内容，烦请帮忙看看，感谢！
我已经调用了最小的 SAM 模型，仍然是跑不了。
但我第一次运行的时候是用了最大的 SAM 模型，是成功运行了的。但之后都不行了，不知道是哪里出了问题。

Start SAM Processing
Initializing SAM
Running SAM Inference (591, 472, 3)
Traceback (most recent call last):
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything-master\scripts\sam.py", line 208, in sam_predict
    predictor.set_image(image_np_rgb)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 234, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 8.00 GiB total capacity; 5.32 GiB already allocated; 744.75 MiB free; 5.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by daizhuo** [comment]
> > 请问换了小模型是什么意思？我已经换了最小那个300多M的SAM模型，仍然是不行啊。
> > 换了l模型就可以跑了，理论上来说你的应该也可以，不应该最小的模型还是跑不了，你看看是不是显存没清掉，重启试一下。

我已经试过多次重启了，换了最小的模型，仍然无解。麻烦帮我看看我的CMD显示内容，谢谢！

**Comment by 3077107162** [comment]
> 

这个内容没什么特别的，就是网络做推理的时候提示显存不足。你用的是哪个版本的ui。

**Comment by 3077107162** [comment]
> > > 请问换了小模型是什么意思？我已经换了最小那个300多M的SAM模型，仍然是不行啊。
> > > 换了l模型就可以跑了，理论上来说你的应该也可以，不应该最小的模型还是跑不了，你看看是不是显存没清掉，重启试一下。
> 
> 我已经试过多次重启了，换了最小的模型，仍然无解。麻烦帮我看看我的CMD显示内容，谢谢！


这个内容没什么特别的，就是网络做推理的时候提示显存不足。你用的是哪个版本的ui。

**Comment by daizhuo** [comment]
谢谢你啊！
我用的是 AUTOMATIC1111 v1.10 最新版本，采用 torch 2.0.0 的这个版本。很奇怪，第一次可以顺利应用，之后就一直不行了。

**Comment by wen313** [comment]
@continue-revolution 感觉可以加一个开关，选择可以使用cpu方式来运行。我这边手动修改了下用cpu方式运行，是可以切图出来的，而且感觉也没有那么慢。
![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/5064580/946fca8a-b1d4-4243-8367-79a9101f7a8a)
