### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by daizhuo** [continue-revolution/sd-webui-segment-anything#81]
我在 WEBUI 目录下：
pip install pycocotools
而且进一步：
pip install --upgrade --force-reinstall pycocotools

还是显示 No module named 'pycocotools'

我是不懂程序，只是想用这个功能，请指教！！谢谢。

Start semantic segmentation with processor seg_ofade20k
Traceback (most recent call last):
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything-master\scripts\sam.py", line 318, in cnet_seg
    register_auto_sam(sam, auto_sam_points_per_side, auto_sam_points_per_batch, auto_sam_pred_iou_thresh,
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything-master\scripts\auto.py", line 273, in register_auto_sam
    global_sam = SamAutomaticMaskGenerator(
  File "C:\Users\Daizho\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\automatic_mask_generator.py", line 118, in __init__
    from pycocotools import mask as mask_utils  # type: ignore # noqa: F401
ModuleNotFoundError: No module named 'pycocotools'

**Comment by continue-revolution** [comment]
#77
