### ISSUE TITLE
whats wrong? 

### ISSUE THREAD

**Issue by toniedeng** [continue-revolution/sd-webui-segment-anything#82]
I use the redraw function to draw a new picture for the background. Using controlnet and segmengt, the following code error occurs

Error running process: G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py
Traceback (most recent call last):
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 761, in process
    process_unit.set_process_attributes(p)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-segment-anything\scripts\process_params.py", line 87, in set_process_attributes
    inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_mask_blur)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-segment-anything\scripts\process_params.py", line 43, in get_input_and_mask
    mask = Image.open(self.dilation_output_gallery[1]['name']).convert('L')
TypeError: 'bool' object is not subscriptable
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 981, in process
    self.enabled_units = self.get_enabled_units(p)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 944, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "G:\AI\sd-webui-aki-v4\webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 796, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'list' object has no attribute 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by continue-revolution** [comment]
I'm not sure about what you mean by "redraw", but I do not expect people to use this feature. You should not upload anything to img2img panel.

**Comment by toniedeng** [comment]
> I'm not sure about what you mean by "redraw", but I do not expect people to use this feature. You should not upload anything to img2img panel.

![497791f7f8072785a06a2eab1c0adb0](https://user-images.githubusercontent.com/130746710/236779335-517aeb95-2574-4ce0-974a-398f46d9d3ed.png)

**Comment by toniedeng** [comment]
> I'm not sure about what you mean by "redraw", but I do not expect people to use this feature. You should not upload anything to img2img panel.

in fact, i want add new background and 2girl in photo.

**Comment by continue-revolution** [comment]
Go to inpaint upload panel and retry.
