### ISSUE TITLE
3060 12G 显存都是运行失败

### ISSUE THREAD

**Issue by daizhuo** [continue-revolution/sd-webui-segment-anything#83]
之前运行得好好的，然后突然失败了，之后就一直不能成功运算了。是不是有 BUG？
我另一台机是 8G 显存，显存不足一次后，就永远不能成功了。即使删除重装都不行。
是不是设置了什么保护机制导致的？
感谢帮忙处理下！！！

以下是我 12G 显存运行时的 CMD 显示内容

Start SAM Processing
Initializing SAM
Running SAM Inference (768, 768, 3)
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything-master\scripts\sam.py", line 208, in sam_predict
    predictor.set_image(image_np_rgb)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 234, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "D:\stable-diffusion-webui-1.1.0\venv\lib\site-packages\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 5.63 GiB already allocated; 4.25 GiB free; 5.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by continue-revolution** [comment]
要么重新启动整台机器，要么把https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/devices.py#L56-L60 复制到终端运行一下

**Comment by daizhuo** [comment]
感谢回复。我重启还是不行，试了无数次了。
我只是用家，对程序一无所知，请原谅哈。
烦请指导。
另外，L56-L60直接复制到终端显示：

Microsoft Windows [Version 10.0.19044.2130]
(c) Microsoft Corporation. All rights reserved.

C:\Users\PC>def torch_gc():
'def' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PC>    if torch.cuda.is_available():
The syntax of the command is incorrect.

C:\Users\PC>        with torch.cuda.device(get_cuda_device_string()):
'with' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PC>            torch.cuda.empty_cache()
'torch.cuda.empty_cache' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PC>            torch.cuda.ipc_collect()

**Comment by continue-revolution** [comment]
先输入python3再跑这些东西。最好是在你虚拟环境下，你自己研究下怎么启动你虚拟环境。

如果你重启没用的话那只有可能是你系统有问题，清不掉显存的缓存。
