### ISSUE TITLE
运行 AutoSAM报错

### ISSUE THREAD

**Issue by daizhuo** [continue-revolution/sd-webui-segment-anything#85]
报错如下，会是什么原因，感谢赐教！

Start semantic segmentation with processor seg_ofade20k
Start SAM Processing
Initializing SAM
Running SAM Inference (218, 231, 3)
SAM inference with 0 box, 1 positive prompts, 1 negative prompts
Creating output image
Start semantic segmentation with processor seg_ofade20k
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\stable-diffusion-webui-1.1.0\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything\scripts\sam.py", line 322, in cnet_seg
    outputs = semantic_segmentation(cnet_seg_input_image, cnet_seg_processor, cnet_seg_processor_res,
  File "D:\AI\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything\scripts\auto.py", line 192, in semantic_segmentation
    if not os.path.isdir(os.path.join(scripts.basedir(), "annotator")) and not create_symbolic_link():
  File "D:\AI\stable-diffusion-webui-1.1.0\extensions\sd-webui-segment-anything\scripts\auto.py", line 30, in create_symbolic_link
    os.symlink(cnet_annotator_dir, sam_annotator_dir, target_is_directory=True)
OSError: [WinError 1314] A required privilege is not held by the client: 'D:\\AI\\stable-diffusion-webui-1.1.0\\extensions\\sd-webui-controlnet/annotator' -> 'D:\\AI\\stable-diffusion-webui-1.1.0\\extensions\\sd-webui-segment-anything\\annotator'

**Comment by continue-revolution** [comment]
你没有controlnet

**Comment by daizhuo** [comment]
https://github.com/Mikubill/sd-webui-controlnet.git   不可能 啊，我装的是这个 controlnet v1.1.150

**Comment by daizhuo** [comment]
> https://blog.csdn.net/lly1122334/article/details/112481535

请问应该对哪个文件进行如上例子操作？
非常抱歉哈，我一点也不懂程序，烦请指教！

**Comment by continue-revolution** [comment]
如果你用的是什么整合包或者启动器，直接管理员模式打开整合包或者启动器；如果你是从命令行启动，右键左下角windows标志打开windows powershell 管理员模式，cd <webui文件夹>，启动webui
